apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-polyttool
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: grafana_ro
      defaultDatabase: polyttool
    secureJsonData:
      password: grafana_readonly_local
    editable: false
